spring:
 datasource:
  url: jdbc:mysql://localhost:3306/method_data?characterEncoding=UTF-8
  username: table_master
  password: masterQ
  driver-class-name: com.mysql.cj.jdbc.Driver
 sql:
  init:
   mode: always
 autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

mybatis:
 configuration:
  map-underscore-to-camel-case: true
 type-aliases-package: dev.itboot.mb.Model
 
logging:
 level:
   org:
    springframework: WARN
   dev:
    itboot:
     mb:
      Mapper:
       MethodMapper: DEBUG
       
  
